// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_prueba.DAL;

namespace api_prueba.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20200731034755_Agregar_campos_Usuarios")]
    partial class Agregar_campos_Usuarios
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("api_prueba.DAO.Interfaces.ADM.Estados", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Estado");

                    b.HasKey("IdEstado");

                    b.ToTable("Estados","ADM");
                });

            modelBuilder.Entity("api_prueba.Model.Roles", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Rol");

                    b.HasKey("IdRol");

                    b.ToTable("Roles","ADM");
                });

            modelBuilder.Entity("api_prueba.Model.Usuarios", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido");

                    b.Property<string>("Contrasenia");

                    b.Property<string>("Correo");

                    b.Property<int>("IdEstado");

                    b.Property<int>("IdRol");

                    b.Property<string>("Nombre");

                    b.Property<string>("Usuario");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios","ADM");
                });

            modelBuilder.Entity("api_prueba.Model.Usuarios", b =>
                {
                    b.HasOne("api_prueba.DAO.Interfaces.ADM.Estados", "estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("api_prueba.Model.Roles", "rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
